import { facebook, instagram, twitter, youtube } from "../assets";
import { FollowerInfo, StatsInfo } from "../common/types";

export const followersData: FollowerInfo[] = [
  {
    id: 1,
    username: "@nathanf",
    totalAmount: "1987",
    todayAmount: "12",
    icon: facebook,
    up: true,
    color: "#178FF5",
  },
  {
    id: 2,
    username: "@nathanf",
    totalAmount: "1044",
    todayAmount: "99",
    icon: twitter,
    up: true,
    color: "#1DA1F2",
  },
  {
    id: 3,
    username: "@realnathanf",
    totalAmount: "11k",
    todayAmount: "1099",
    icon: instagram,
    up: true,
    color: "linear-gradient(225deg, #DF4896 0%, #EE877E 50.91%, #FDC366 100%)",
  },
  {
    id: 4,
    username: "Nathan F.",
    totalAmount: "8239",
    todayAmount: "144",
    icon: youtube,
    up: false,
    color: "#C4032B",
  },
];

export const statsInfo: StatsInfo[] = [
  {
    id: 5,
    header: "Page Views",
    totalAmount: "87",
    todayAmount: "3",
    icon: facebook,
    up: true,
  },
  {
    id: 6,
    header: "Likes",
    totalAmount: "52",
    todayAmount: "2",
    icon: facebook,
    up: false,
  },
  {
    id: 7,
    header: "Likes",
    totalAmount: "5462",
    todayAmount: "2257",
    icon: instagram,
    up: true,
  },
  {
    id: 8,
    header: "Profile Views",
    totalAmount: "52k",
    todayAmount: "1375",
    icon: instagram,
    up: true,
  },
  {
    id: 9,
    header: "Retweets",
    totalAmount: "117",
    todayAmount: "303",
    icon: twitter,
    up: true,
  },
  {
    id: 10,
    header: "Likes",
    totalAmount: "507",
    todayAmount: "553",
    icon: twitter,
    up: true,
  },
  {
    id: 11,
    header: "Likes",
    totalAmount: "107",
    todayAmount: "19",
    icon: youtube,
    up: false,
  },
  {
    id: 12,
    header: "Total Views",
    totalAmount: "1407",
    todayAmount: "12",
    icon: youtube,
    up: false,
  },
];
